In [15]:
import numpy as np
import numpy as np

In [2]:
# サンプル用のアレイを作る
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
# 転置
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [4]:
# transposeメソッドでも可能
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [5]:
# 引き数をとれる。0は行、1は列
arr.transpose((0,1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# 行と列が入れ替わる
arr.transpose((1,0))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [7]:
# swapaxesは、どれとどれを入れ替えるか。
arr.swapaxes(1,0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [8]:
arr.swapaxes(0,1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [9]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
# 行列のかけ算
np.dot(arr.T, arr)
# 45 = 0*0 + 3*3+ 6*6
np.dot(arr,arr.T)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [11]:
# 3次元行列
arr3d = np.arange(12).reshape((3,2,2))
arr3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [12]:
arr3d[0]

array([[0, 1],
       [2, 3]])

In [13]:
# 3次元行列の転置も可能
arr3d.transpose((0,2,1))

array([[[ 0,  2],
        [ 1,  3]],

       [[ 4,  6],
        [ 5,  7]],

       [[ 8, 10],
        [ 9, 11]]])