In [7]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [2]:
arr1= np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ser1 = Series([0,1,2],index=list('tuv'))

In [9]:
ser2= Series([4,5],index=list('xy'))

In [10]:
ser1

t    0
u    1
v    2
dtype: int64

In [11]:
ser2

x    4
y    5
dtype: int64

In [12]:
pd.concat([ser1,ser2])

t    0
u    1
v    2
x    4
y    5
dtype: int64

In [13]:
pd.concat([ser1,ser2,ser1])

t    0
u    1
v    2
x    4
y    5
t    0
u    1
v    2
dtype: int64

In [14]:
pd.concat([ser1,ser2],axis=1)

0    1
t  0.0  NaN
u  1.0  NaN
v  2.0  NaN
x  NaN  4.0
y  NaN  5.0

In [15]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  t    0
      u    1
      v    2
cat2  x    4
      y    5
dtype: int64

In [16]:
pd.concat([ser1,ser2],axis=1,keys=['key1','key2'])

key1  key2
t   0.0   NaN
u   1.0   NaN
v   2.0   NaN
x   NaN   4.0
y   NaN   5.0

In [19]:
dframe1 = DataFrame(np.random.randn(4,3),columns=list('xyz'))

In [20]:
dframe1

x         y         z
0  0.957798  1.529691 -0.280487
1  1.872167  0.404852 -0.428335
2  0.100691  1.415883  0.922682
3  0.858549 -1.115470 -2.125741

In [21]:
dframe2 = DataFrame(np.random.randn(3,3),columns = list('yqx'))

In [22]:
dframe2

y         q         x
0 -2.028931 -0.266661  2.584339
1 -0.855733 -0.508549  0.668081
2 -0.328551  0.914774  1.136990

In [24]:
pd.concat([dframe1,dframe2])

q         x         y         z
0       NaN  0.957798  1.529691 -0.280487
1       NaN  1.872167  0.404852 -0.428335
2       NaN  0.100691  1.415883  0.922682
3       NaN  0.858549 -1.115470 -2.125741
0 -0.266661  2.584339 -2.028931       NaN
1 -0.508549  0.668081 -0.855733       NaN
2  0.914774  1.136990 -0.328551       NaN

In [25]:
pd.concat([dframe1,dframe2], ignore_index=True)

q         x         y         z
0       NaN  0.957798  1.529691 -0.280487
1       NaN  1.872167  0.404852 -0.428335
2       NaN  0.100691  1.415883  0.922682
3       NaN  0.858549 -1.115470 -2.125741
4 -0.266661  2.584339 -2.028931       NaN
5 -0.508549  0.668081 -0.855733       NaN
6  0.914774  1.136990 -0.328551       NaN